# Generated by Django 3.0.4 on 2020-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gamegroup_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
