# Generated by Django 3.0.4 on 2020-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200323_2122'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_application'),
        ),
        migrations.AddConstraint(
            model_name='attending',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_attendee'),
        ),
    ]
