# Generated by Django 3.0.4 on 2020-03-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200324_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='attending',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.GameGroup'),
            preserve_default=False,
        ),
    ]
